Library/Library/Controllers/LibraryController.cs
using Library.Common.Models;
using Library.Common.ViewModels;
using Library.Extensions;
using Library.Logic.Logics;
using Library.Models;
using Library.Services.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Serilog;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Google.Apis.Books.v1;
using Google.Apis.Services;
using System.Net.Http;

namespace Library.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class LibraryController : Controller
    {
        private readonly ILibraryLogic _libraryLogic;
        private readonly IBookService _bookService;
        private readonly IUserService _userService;
        private readonly IKeyWordService _keyWordService;
        private readonly IBookApiService _bookApiService;
        private readonly ILogger _logger;

        public LibraryController(ILibraryLogic libraryLogic, IBookService bookService, IUserService userService, IKeyWordService keyWordService, ILogger logger, IBookApiService bookApiService)
        {
            _libraryLogic = libraryLogic;
            _bookService = bookService;
            _userService = userService;
            _keyWordService = keyWordService;
            _logger = logger;
            _bookApiService = bookApiService;
        }

        /// <summary>
        /// Показывает страницу создания новой книги
        /// </summary>
        /// <returns> Результат создания </returns>
        [HttpGet("Books/[action]")]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateBook()
        {
            return View();
        }

        /// <summary>
        /// Показывает карточку книги
        /// </summary>
        /// <param name="bookId"> Id книги </param>
        /// <returns> Результат получения книги по Id </returns>
        [HttpGet("Books/[action]")]
        [Authorize(Roles = "User, Admin")]
        public IActionResult BookCard(Guid bookId)
        {
            var result = _libraryLogic.GetBookCard(bookId, this.CurrentUser());
            return View(result);
        }

        /// <summary>
        /// Вывод частичного представления "Справочник ключевых слов"
        /// </summary>
        /// <param name="name"> Введенное слово на странице </param>
        /// <returns> Вывод частичного представления </returns>
        [HttpPost("Books/SelectKeyWords")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult SelectKeyWords([FromForm] string name)
        {
            var result = _keyWordService.GetAll();
            result = result.Where(word => word.ToLower().Contains(name.ToLower())).Take(3).ToList();
            return PartialView(result);
        }

        /// <summary>
        /// Вывод частичного предстваления списка книг
        /// </summary>
        /// <param name="pageInfo"> Модель с некоторой информацией о странице</param>
        /// <param name="model">Модель поиска книг</param>
        /// <returns>Вывод частичного представления списка книг</returns>
        [HttpPost("Books/[action]")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult ListBooks([FromForm] PageInfoModel pageInfo, [FromForm] SearchViewModel model)
        {
            ListBooksViewModel result = null;

            switch (pageInfo.ActionName.Replace("/", ""))
            {
                case "AllBooks":
                    result = _libraryLogic.GetAllBook(this.CurrentUser(), model);
                    break;
                case "CurrentReadList":
                    result = _libraryLogic.GetCurrentReadBooks(this.CurrentUser(), model);
                    break;
                case "PreviousReadList":
                    result = _libraryLogic.GetPreviousReadBooks(this.CurrentUser(), model);
                    break;
            }

            if (result != null)
            {
                result.PageView = pageInfo.PageItems;

                if (pageInfo.PageItems == 1)
                {
                    pageInfo.PageItems = 4;
                }

                result.Search = model;

                ViewBag.Pagination = Pagination(pageInfo, result);

                result.Books = result.Books.OrderByDescending(book => (book.Aviable != 0)).ThenBy(book => book.Title).Skip((pageInfo.Page - 1) * pageInfo.PageItems).Take(pageInfo.PageItems).ToList();

                return PartialView(result);
            }
            return PartialView(result);
        }

        /// <summary>
        /// Показывает страницу со списком всех книг
        /// </summary>
        /// <returns> Результат вывода книг </returns>
        [HttpGet("Books/[action]")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AllBooks()
        {
            return View();
        }

        /// <summary>
        /// Показывает страницу со списком книг текущего пользователя 
        /// </summary>
        /// <returns> Результат вывода книг </returns>
        [HttpGet("Books/[action]")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult CurrentReadList()
        {
            return View();
        }

        /// <summary>
        /// Показывает страницу со списком прочитанных пользователем книг
        /// </summary>
        /// <returns> Результат вывода книг </returns>
        [HttpGet("Books/[action]")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult PreviousReadList()
        {
            return View();
        }

        /// <summary>
        /// Возвращает представление со списком действий с книгой
        /// </summary>
        /// <param name="bookId"> Id книги </param>
        /// <param name="count"> Количество возвращаемых записей </param>
        /// <param name="countRequest"> Количество предыдущих запросов </param>
        /// <returns> Представление со списком действий </returns>
        [HttpPost("Logs/[action]")]
        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> LogsBook([FromForm] Guid bookId, [FromForm] int count = 5, [FromForm] int countRequest = 0)
        {
            var result = await _libraryLogic.GetLogsBook(bookId, count, countRequest);
            return View(result);
        }
        /// <summary>
        /// Возвращает представление со списком активных пользователей книги
        /// </summary>
        /// <param name="bookId"> Id книги </param>
        /// <param name="count"> Количество возвращаемых записей </param>
        /// <param name="countRequest"> Количество предыдущих запросов </param>
        /// <returns> Представление со списком активных пользователей книги </returns>
        [HttpPost("Holders/[action]")]
        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> HoldersBook([FromForm] Guid bookId, [FromForm] int count = 5, [FromForm] int countRequest = 0)
        {
            var result = await _libraryLogic.GetHolderBook(bookId, count, countRequest);
            return View(result);
        }

        /// <summary>
        /// Проверка используется ли книга пользователем
        /// </summary>
        /// <param name="bookId"> Id книги </param>
        /// <returns> Результат проверки </returns>
        [HttpPost("Books/[action]")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult CheckBook([FromForm] Guid bookId)
        {
            _libraryLogic.CheckBook(bookId);
            return Ok("Книге никем не используется");
        }
        /// <summary>
        /// Запрос на создание книги
        /// </summary>
        /// <param name="model"> Модель книги </param>
        /// <returns> Результат создания книги </returns>
        [HttpPost("Books/[action]")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateBook([FromForm] BookViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Создание книги невозможно, проверьте введенные данные и повторите попытку");
            }
            await _libraryLogic.Create(model);
            return Ok("Книга успешно добавлена");
        }

        /// <summary>
        /// Показывает страницу изменения книги
        /// </summary>
        /// <param name="bookId"> Id книги </param>
        /// <returns> Страница изменения книги </returns>
        [HttpGet("Books/EditBook")]
        [Authorize(Roles = "Admin")]
        public IActionResult EditBook(Guid bookId)
        {
            var result = _libraryLogic.GetBook(bookId);
            return View(result);
        }

        /// <summary>
        /// Запрос на изменение книги
        /// </summary>
        /// <param name="model"> Модель измененной книги </param>
        /// <returns> Результат изменения </returns>
        [HttpPut("Books/[action]")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateBook([FromForm] BookViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("При изменении книги произошла ошибка, данные заполнены не верно");
            }
            var url = Request.GetDisplayUrl();
            await _libraryLogic.Update(model, url);
            return Ok("Книга успешно изменена");
        }

        /// <summary>
        /// Запрос на удаление книги
        /// </summary>
        /// <param name="bookId"> Id книги </param>
        /// <returns> Результат удаления книги </returns>
        [HttpDelete("Books/[action]")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteBook([FromForm] Guid bookId)
        {
            await _bookService.Delete(bookId);
            return Ok("Книга успешно удалена");
        }

        /// <summary>
        /// Запрос на получение книги
        /// </summary>
        /// <param name="bookId"> Id книги </param>

Library/Library/Controllers/SettingsController.cs
using Library.Common.ViewModels;
using Library.Services.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System.Threading.Tasks;

namespace Library.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class SettingsController : Controller
    {

        private readonly ISettingsService _settingsService;
        private readonly ILogger _logger;
        public SettingsController(ISettingsService settingsService, ILogger logger)
        {
            _settingsService = settingsService;
            _logger = logger;
        }

        /// <summary>
        /// Показывает все настройки системы, связанные с рассылкой почты
        /// </summary>
        /// <returns>Результат вывода настроек</returns>
        [HttpGet("[action]")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AllSettings()
        {
            var settings = await _settingsService.GetSettings();
            return View(settings);
        }

        /// <summary>
        /// Изменение настроек системы
        /// </summary>
        /// <param name="model">Модель представления настроек системы</param>
        /// <returns>Результат изменения настроек</returns>
        [HttpPut("[action]")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ChangeSettings([FromForm] SettingsViewModel model)
        {
            await _settingsService.ChangeSettingsAsync(model);
            return Ok("Настройки успешно сохранены");
        }
    }
}

Library/Library/Views/Shared/SelectKeyWords.cshtml
@model List<string>
@{
    ViewData["Title"] = "_SelectKeyWords";
}
@if (Model != null && Model.Count != 0)
{
    <div class="dropdown" id="drop">
        <div class="dropdown-menu show" aria-labelledby="dropdownMenu1">
            @foreach (var name in Model)
            {
                <a class="dropdown-item keywordItemDrop" href="#">@name</a>
            }
        </div>
    </div>

}

Library/Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Library</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <link href="~/fonts/Segoe UI/stylesheet.css" rel="stylesheet" type="text/css" />
    <link href="~/css/jquery.rating.css" rel="stylesheet" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/BookListHub.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-0">
            <div class="container text-header">
                <a class="navbar-brand clearSearch" href="~/Library/Books/AllBooks">ММТР библиотека</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.IsInRole("User") || User.IsInRole("Admin"))
                {<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item" style="margin-right:2%;margin-left:2%;">
                                <a class="nav-link text-dark clearSearch" asp-area="" asp-controller="Library" asp-action="AllBooks">Все книги</a>
                            </li>
                            <li class="nav-item">
                                <div class="btn-group" role="group">
                                    <button id="btnGroupDrop1" type="button" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: #222222 !important;  border: none;">
                                        Мои книги
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                        <a class="dropdown-item " asp-action="CurrentReadList" asp-controller="Library">Читаю</a>
                                        <a class="dropdown-item" asp-action="PreviousReadList" asp-controller="Library">Прочитано</a>
                                    </div>
                                </div>

                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item" style="width:40%">

                                </li>
                                <li class="nav-item" style="margin-right:1%">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="CreateBook">Добавить книгу</a>
                                </li>
                                <li class="nav-item" style="margin-right:2%">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="AllSettings">Настройки</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item" style="width:66%"></li>

                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="logOut" href="#">Выйти</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                }
            </div>
        </nav>

    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* Модальное окно для уведомления о успешном действии с последующей переадресацией на другую страницу или обновлением списка *@
    <div id="ModalDialog" class="modal fade">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <h4 class="modal-title hidden" id="raitingH"> Оцените прочитанную книгу</h4>
                <div class="modal-header">
                    <h4 class="modal-title" id="h"></h4>
                </div>
                <br />
                <button id="ModalBut" type="button" class="btn btn-primary btn-modal"> Ок </button>
            </div>
        </div>
    </div>

    @* Модальное окно для различных уведомлений без последующих действий*@
    <div id="ModalInfo" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="hInfo"></h4>
                </div>
                <br />
                <button id="OkBut" onclick="hideModalInfo();" type="button" class="btn btn-primary btn-modal"> Ок </button>
            </div>
        </div>
    </div>

    @* Модальное окно с уведомлением об ошибке*@
    <div id="ErrorInfo" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="ErrorH"></h4>
                </div>
                <br />
                <button id="ErrorBut" onclick="hideErrorInfo();" type="button" class="btn btn-primary btn-modal"> Ок </button>
            </div>
        </div>
    </div>

    @* Модальное окно с подтверждением удаления книги*@
    <div id="ConfirmDelete" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Вы действительно хотите удалить эту книгу? Данное действие будет необратимо </h4>
                </div>
                <br />
                <div class="modal-footer">
                    <button id="ConfirmDeleteBut" type="button" class="btn btn-primary"> Подтверждаю </button>
                    <button id="CancelButDelete" onclick="hideConfirmDelete();" type="button" class="btn btn-dark"> Отмена </button>
                </div>
            </div>
        </div>
    </div>

    @* Модальное окно с подтверждением возврата книги*@
    <div id="ConfirmReturn" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Вы действительно хотите вернуть данную книгу? </h4>
                </div>
                <br />
                <div class="modal-footer">
                    <input type="hidden" id="IdReturnBook" value="" />
                    <button id="ConfirmReturnBut" type="button" class="btn btn-primary"> Подтверждаю </button>
                    <button id="CancelButReturn" onclick="hideConfirmReturn();" type="button" class="btn btn-dark"> Отмена </button>
                </div>
            </div>
        </div>
    </div>

    @* Модальное окно с подтверждением выхода из аккаунта*@
    <div id="ConfirmLogOut" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Вы действительно хотите выйти из аккаунта? </h4>
                </div>
                <br />
                <div class="modal-footer">
                    <button id="ConfirmLogOutBut" type="button" class="btn btn-primary"> Подтверждаю </button>
                    <button id="CancelButLogOut" onclick="hideConfirmLogOut();" type="button" class="btn btn-dark"> Отмена </button>
                </div>
            </div>
        </div>
    </div>

    @* Модальное окно с подтверждением оценивания книги*@
    <div id="ConfirmRaiting" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Вы действительно хотите поставтить этой книге оценку <b id="score"></b></h4>
                </div>
                <br />
                <div class="modal-footer">
                    <button id="ConfirmRaitingBut" type="button" class="btn btn-primary  btn-modal"> Подтверждаю </button>
                    <button id="CancelButRaiting" type="button" class="btn btn-dark"> Отмена </button>
                </div>
            </div>
        </div>
    </div>

    @* Модальное окно с подтверждением оценивания книги*@
    <div id="ConfirmRaitingReturned" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" style="display: block;">
                    <h4 class="modal-title" id="RaitingH"></h4>

                    <div id="raitingModal" class="hidden" style="margin-left: 30%;">
                        <input type="hidden" name="val" value="0">
                        <input type="hidden" name="votes" value="0">
                        <input type="hidden" name="vote-id" value="modal1">
                        <input type="hidden" name="cat_id" value="2">
                    </div>

                </div>
                <br />
                <div class="modal-footer" style="margin-right: 35%;">
                    <button id="NextBut" type="button" class="btn btn-primary  btn-modal"> Продолжить </button>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer text-muted">
        Библиотека ММТР V 5.0
    </footer>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script type="text/javascript">

        $('.clearSearch').click(function () {

            localStorage.setItem("SearchName", null);
            localStorage.setItem("SearchCategory", 0);

        });
    </script>
    <script src="~/js/functions.js" asp-append-version="true"></script>
    <script src="~/js/Ajax.js" asp-append-version="true"></script>
    <script src="~/js/ModalDialog.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js" asp-append-version="true"></script>
    <script src="~/lib/inputmask/inputmask.min.js" asp-append-version="true"></script>
    <script src="~/lib/inputmask/jquery.inputmask.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-raiting/jquery.rating-2.0.min.js" asp-append-version="true"></script>
    <script src="~/js/ModalWindowsFunctions.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Library/Library/Views/Shared/_Pagination.cshtml
@model Pagination;
    <ul class="pagination">
        <li class="pagination prevPage @(Model.Pages[0].IsCurrenPage ? "active" : "") @(Model.Pages[0].Disabled ? "disabled" : "")">
            <a href="@Url.RouteUrl(Model.Pages[0].RouteValues.ToRouteValueDictionary())">@Html.Raw(Model.Pages[0].Caption)</a>
        </li>
        @for (var i = 1; i < Model.Pages.Count - 1; i++)
        {
            <li class="pagination @(Model.Pages[i].IsCurrenPage ? "active" : "") @(Model.Pages[i].Disabled ? "disabled" : "")">
                <a href="@Url.RouteUrl(Model.Pages[i].RouteValues.ToRouteValueDictionary())" class="@(Model.Pages[i].IsCurrenPage ? "active" : "")">@Html.Raw(Model.Pages[i].Caption)</a>

            </li>

        }
        <li class="pagination nextPage @(Model.Pages[Model.Pages.Count-1].IsCurrenPage ? "active" : "") @(Model.Pages[Model.Pages.Count-1].Disabled ? "disabled" : "")">
            <a href="@Url.RouteUrl(Model.Pages[Model.Pages.Count-1].RouteValues.ToRouteValueDictionary())">@Html.Raw(Model.Pages[Model.Pages.Count - 1].Caption)</a>
        </li>
    </ul>